const moods = {
  afrobeat:        { color:"#f39c12", emoji:"🎧", playlist:"https://open.spotify.com/playlist/6xwBhWuFwOySNZtxDZjzcS?si=M9CmA9pMQmSJoQk6xsqvXA" },
  gospel:         { color:"#27ae60", emoji:"🙏", playlist:"https://open.spotify.com/playlist/4XghvDfM1IIBAbH8A5zVJw" },
  love:           { color:"#e84393", emoji:"❤️", playlist:"https://open.spotify.com/playlist/54NligNynYpYlfzyEfwQJX?si=NIVi2gdFRFafg71tpT5KMw" },
  throwback:      { color:"#d35400", emoji:"🕰️", playlist:"https://open.spotify.com/playlist/6arfDf4SYVDaDCbXDOLOcg?si=QIIshYyAQ7yF1QKvT9-WjA&pi=ab7EkJvAT7Sj5" },
  chill:          { color:"#3498db", emoji:"😌", playlist:"https://open.spotify.com/playlist/37i9dQZF1EVHGWrwldPRtj?si=muV4Fbg2SUWe9xUBmZA_dg" },
  party:          { color:"#f1c40f", emoji:"🎉", playlist:"https://open.spotify.com/playlist/5g6lg8pRELNAi0QAJORbYT?si=HLw8xovISU6SV623EPNC-w" },
  sad:            { color:"#34495e", emoji:"😢", playlist:"https://open.spotify.com/playlist/0XaVOCiMsOVZ3fFQsmiZ54?si=kur_5f3wSuydZs6XhD9Pkg&pi=wbf-w4y1QgmEN" },
  motivation:     { color:"#2c3e50", emoji:"💪", playlist:"https://open.spotify.com/playlist/78Suoigk80gI9mI9z5tYl8?si=RIKwfrV6Rvm2oz6OFD6ZiA&pi=F_G4xntPSLeIx" },
  focus:          { color:"#1abc9c", emoji:"🧠", playlist:"https://open.spotify.com/playlist/6bnfXsKx2VA8Mx8kheMuhj" },
  lofi:           { color:"#7f8c8d", emoji:"🛋️", playlist:"https://open.spotify.com/playlist/6bnfXsKx2VA8Mx8kheMuhj" },
  gospelHits:     { color:"#27ae60", emoji:"🎵", playlist:"https://open.spotify.com/playlist/6lFNiwRFah3b0mE9t50PjJ?si=HkqtFH6kS9KrwhYlbwDHxw" },
  afroPop:        { color:"#e67e22", emoji:"🔥", playlist:"https://open.spotify.com/playlist/37i9dQZF1DWYs2pvwxWA7l?si=KzqA9oHZSLiheSZMb3mw1w&pi=Pc3hFdt2RMqds" },
  drill:          { color:"#8e44ad", emoji:"⚡", playlist:"https://open.spotify.com/playlist/1yjJHl0gxPRNBGQAhIczEj?si=0YdgSqTlTdmCWZAu-nDy6Q&pi=es002BizS_SVs" },
  heartbroken:    { color:"#c0392b", emoji:"💔", playlist:"https://open.spotify.com/playlist/1tX9jfDdDqTE86QuO9MIEA" },
  energetic:      { color:"#e74c3c", emoji:"⚡", playlist:"https://open.spotify.com/playlist/37i9dQZF1EIeEZPgsd7pko?si=KbqaFmcwSBiUX2oHkc9Ovg&pi=aoJ85JK4TgGnR" },
  study:          { color:"#95a5a6", emoji:"📚", playlist:"https://open.spotify.com/playlist/3jvd7h6ZwgpmpJkUxciyRd?si=er0fcTA3Sti-HWsDVBKAUA" },
  nostalgic:      { color:"#b2bec3", emoji:"🗓️", playlist:"https://open.spotify.com/playlist/7fOJBJUoFNnqvs4ISEKWwh?si=1fNMXhz8S_CgxGt9IjmmYw" },
  romantic:       { color:"#e84393", emoji:"💘", playlist:"https://open.spotify.com/playlist/4cJ8qUzt5CSTE9XN5uK2z2?si=fAwL20o5Tlmz5vvRlbS4-g&pi=gU-kkuyGSleRO" },
  rainyDay:       { color:"#0984e3", emoji:"🌧️", playlist:"https://open.spotify.com/playlist/6bnfXsKx2VA8Mx8kheMuhj" },
  roadTrip:       { color:"#d35400", emoji:"🚗", playlist:"https://open.spotify.com/playlist/37i9dQZF1DX2MyUCsl25eb" }
};
